
default: &default
  adapter: postgresql
  encoding: unicode
  # host: localhost 
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: fortus_dev
production:
  <<: *default
  database: fortus-netsuite-hubspot_production
  username: fortus-netsuite-hubspot
  password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>
