
default: &default
  adapter: postgresql
  encoding: unicode
  # host: localhost 
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: fortus_dev

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>

  cable:
      url: <%= ENV['DATABASE_URL'] %>
      pool: 5
  queue:
      url: <%= ENV['DATABASE_URL'] %>
      pool: 5
