
default: &default
  adapter: postgresql
  encoding: unicode
  # host: localhost 
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: fortus_dev

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

